repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: dotnet-tool-restore
        name: dotnet tool restore
        entry: dotnet tool restore
        language: system
        pass_filenames: false

      - id: dotnet-restore
        name: dotnet restore
        entry: dotnet restore
        language: system
        pass_filenames: false

      - id: csharpier-check
        name: csharpier check
        entry: dotnet csharpier check .
        language: system
        pass_filenames: false

      - id: dotnet-format
        name: dotnet format
        entry: dotnet format --verify-no-changes --no-restore
        language: system
        pass_filenames: false

      - id: dotnet-build
        name: dotnet build
        entry: dotnet build --no-restore
        language: system
        pass_filenames: false

      - id: dotnet-test
        name: dotnet test
        entry: dotnet test --no-restore
        language: system
        pass_filenames: false
