services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap-local
    hostname: openldap
    environment:
      LDAP_ORGANISATION: Example Company
      LDAP_DOMAIN: example.org
      LDAP_ADMIN_PASSWORD: admin
      LDAP_CONFIG_PASSWORD: config
      LDAP_TLS: "false"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin-local
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8081:80"
    depends_on:
      - openldap
volumes:
  ldap_data:
  ldap_config:
